# FILE: render.yaml
services:
  - type: web
    name: sklearntrack-backend
    env: python
    buildCommand: |
      cd sklearntrack_backend
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: |
      cd sklearntrack_backend && gunicorn sklearntrack_backend.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sklearntrack-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "sk-learntrack.onrender.com,localhost,127.0.0.1"